export const spanishLabels: { [key: string]: string } = {
  name: "Nombre",
  calories: "Calorías",
  protein: "Proteínas",
  totalFat: "Grasa Total",
  carbohydrates: "Carbohidratos",
  saturatedFat: "Grasa Saturada",
  transFat: "Grasa Trans",
  cholesterol: "Colesterol",
  sodium: "Sodio",
  dietaryFiber: "Fibra Dietética",
  sugar: "Azúcar",
  addedSugar: "Azúcar Añadida",
  vitaminA: "Vitamina A",
  vitaminC: "Vitamina C",
  vitaminD: "Vitamina D",
  iron: "Hierro",
  calcium: "Calcio",
  zinc: "Zinc",
  water: "Agua",
};
