export const spanishLabels: { [key: string]: string } = {
  name: "Nombre",
  calories: "Calorías (Kcal)",
  proteins: "Proteínas (g)",
  totalFats: "Grasa Total (g)",
  carbohydrates: "Carbohidratos (g)",
  saturatedFats: "Grasa Saturada (g)",
  transFats: "Grasa Trans (mg)",
  cholesterol: "Colesterol (mg)",
  sodium: "Sodio (mg)",
  dietaryFiber: "Fibra Dietaria (g)",
  sugar: "Azúcar (g)",
  addedSugar: "Azúcar Añadida (g)",
  vitaminA: "Vitamina A (µg de ER)",
  vitaminC: "Vitamina C (mg)",
  vitaminD: "Vitamina D (mg o UI)",
  iron: "Hierro (mg)",
  calcium: "Calcio (mg)",
  zinc: "Zinc (mg)",
  water: "Agua (%)",
};
