export const spanishLabels: { [key: string]: string } = {
  calories: "Calorías (Kcal)",
  totalFats: "Grasa Total",
  saturatedFats: "Grasa saturada",
  transFat: "Grasa trans",
  carbohydrates: "Carbohidratos totales",
  dietaryFiber: "Fibra dietaria",
  sugar: "Azúcares totales",
  addedSugar: "Azúcares añadidos",
  proteins: "Proteína",
  sodium: "Sodio",
  vitaminA: "Vitamina A",
  vitaminC: "Vitamina C",
  vitaminD: "Vitamina D",
  calcium: "Calcio",
  iron: "Hierro",
  zinc: "Zinc",
  water: "Agua",
};

export const englishLabels: { [key: string]: string } = {
  calories: "Calories (Kcal)",
  totalFats: "Total Fat",
  saturatedFats: "Saturated Fat",
  transFat: "Trans Fat",
  carbohydrates: "Total Carbohydrate",
  dietaryFiber: "Dietary Fiber",
  sugar: "Total Sugars",
  addedSugar: "Added Sugars",
  proteins: "Protein",
  sodium: "Sodium",
  vitaminA: "Vitamin A",
  vitaminC: "Vitamin C",
  vitaminD: "Vitamin D",
  calcium: "Calcium",
  iron: "Iron",
  zinc: "Zinc",
  water: "Water",
};

export const units: { [key: string]: string } = {
  calories: "",
  totalFats: "g",
  saturatedFats: "g",
  transFat: "g",
  carbohydrates: "g",
  dietaryFiber: "g",
  sugar: "g",
  addedSugar: "g",
  proteins: "g",
  sodium: "mg",
  vitaminA: "µg",
  vitaminC: "mg",
  vitaminD: "µg",
  calcium: "mg",
  iron: "mg",
  zinc: "mg",
  water: "g",
};
