export const rawMaterial = {
  name: "",
  calories: undefined,
  proteins: undefined,
  totalFats: undefined,
  carbohydrates: undefined,
  saturatedFats: undefined,
  transFats: undefined,
  cholesterol: undefined,
  sodium: undefined,
  dietaryFiber: undefined,
  sugar: undefined,
  addedSugar: undefined,
  vitaminA: undefined,
  vitaminC: undefined,
  vitaminD: undefined,
  iron: undefined,
  calcium: undefined,
  zinc: undefined,
  water: undefined,
};
